/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.47).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.ionuth.api;

import io.ionuth.api.model.HelloMessage;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import java.util.List;
import java.util.Map;


@Validated
@Api(value = "Hello", description = "the Hello API")
public interface HelloApi {

    @ApiOperation(value = "returns hello", nickname = "sayHello", notes = "says hello world", response = HelloMessage.class, tags={ "hello", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = HelloMessage.class) })
    @RequestMapping(value = "/api/v1/hello",
        produces = { "application/xml", "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<HelloMessage> sayHello();

}

