openapi: 3.0.3
info:
  version: 1.0.0
  title: Sample Hello World App
  description: Hello World API developed designed using OpenAPI specifications
tags:
  - name: hello
    description: operations about saying hello
    
paths:
  '/api/v1/hello':
    get:
      tags: 
        - hello
      summary: returns hello
      description: says hello world
      operationId: sayHello
      responses:
        200:
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Customer'
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'

components:
  schemas:
    Customer:
      type: object
      properties:
        id:
          type: integer
          format: int64
        firstName:
          type: string
        lastName:
          type: string
      xml: 
        name: Customer 